sequelize requires a `where` parameter for `model.destroy`
This was the error being generated: 
Error: Missing where or truncate attribute in the options parameter of model.destroy.